<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>requestItem</name>
   <tag></tag>
   <elementGuidId>b2f03e0d-f5af-4589-87ce-79d5d22eea39</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <locator>//android.widget.TextView[@resource-id=&quot;com.hdbank.ipaper:id/tv_title_item&quot; and @text=&quot;${requestName}&quot;]/parent::android.widget.LinearLayout/parent::android.widget.RelativeLayout</locator>
   <locatorCollection>
      <entry>
         <key>ID</key>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector()</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//android.widget.TextView[@resource-id=&quot;com.hdbank.ipaper:id/tv_title_item&quot; and @text=&quot;${requestName}&quot;]/parent::android.widget.LinearLayout/parent::android.widget.RelativeLayout</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
      </entry>
      <entry>
         <key>CUSTOM</key>
      </entry>
      <entry>
         <key>NAME</key>
      </entry>
   </locatorCollection>
   <locatorStrategy>XPATH</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
