<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>priorityValue</name>
   <tag></tag>
   <elementGuidId>f7cc8c2b-8d90-4ba3-aff9-b186b490fda4</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <locator>(//XCUIElementTypeButton[@name=&quot;ic edit pen&quot;])[1]/preceding-sibling::*[1]
</locator>
   <locatorCollection>
      <entry>
         <key>ANDROID_VIEWTAG</key>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
      </entry>
      <entry>
         <key>ID</key>
         <value>com.hdbank.ipaper:id/tv_value_priority</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector()</value>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//XCUIElementTypeButton[@name=&quot;ic edit pen&quot;])[1]/preceding-sibling::*[1]
</value>
      </entry>
      <entry>
         <key>CUSTOM</key>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
      </entry>
      <entry>
         <key>NAME</key>
      </entry>
   </locatorCollection>
   <locatorStrategy>XPATH</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
