<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description>//android.widget.EditText[@resource-id=&quot;com.hdbank.ipaper:id/edit_text_value_phone_number&quot;]</description>
   <name>phoneNumber</name>
   <tag></tag>
   <elementGuidId>341c4ec2-6c12-49ae-ab12-91ad608a937f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <locator>//android.widget.EditText[@resource-id=&quot;com.hdbank.ipaper:id/edit_text_value_phone_number&quot;]</locator>
   <locatorCollection>
      <entry>
         <key>ACCESSIBILITY</key>
      </entry>
      <entry>
         <key>ATTRIBUTES</key>
      </entry>
      <entry>
         <key>NAME</key>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
      </entry>
      <entry>
         <key>IMAGE</key>
      </entry>
      <entry>
         <key>CUSTOM</key>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//android.widget.EditText[@resource-id=&quot;com.hdbank.ipaper:id/edit_text_value_phone_number&quot;]</value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
      </entry>
      <entry>
         <key>ID</key>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector()</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>XPATH</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
